# Generated by Django 4.1.1 on 2022-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='articles_covers')),
                ('date', models.DateField(blank=True, null=True)),
                ('article', models.TextField()),
                ('act', models.CharField(choices=[('Akt I', 'Akt I'), ('Akt II', 'Akt II'), ('Akt III', 'Akt III'), ('Inne', 'Inne')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
