# Generated by Django 4.1.1 on 2022-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField()),
                ('department', models.TextField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=128, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='authors_portraits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
